'use strict';

module.exports = {
  ADD_NEW_PROP_GROUP: 'ADD_NEW_PROP_GROUP',
  EDIT_PROP_GROUP: 'EDIT_PROP_GROUP',
  ADD_WINNING_PROP: 'ADD_WINNING_PROP',
  PLACE_BET: 'PLACE_BET',
  ADD_LINE_ADJUSTMENT: 'ADD_LINE_ADJUSTMENT',
  BUY_BACK_BET: 'BUY_BACK_BET',
  SET_NEW_APP_STATE: 'SET_NEW_APP_STATE',
  REDUX_INIT_ACTION: '@@redux/INIT',
  // Protocol actions
  NOTIFY_AUTHENTICATION: 'NOTIFY_AUTHENTICATION'
};
