'use strict';

module.exports = {
  ADD_NEW_PROP_GROUP: 'ADD_NEW_PROP_GROUP',
  SET_NEW_APP_STATE: 'SET_NEW_APP_STATE',
  REDUX_INIT_ACTION: '@@redux/INIT',
  // Protocol actions
  NOTIFY_AUTHENTICATION: 'NOTIFY_AUTHENTICATION'
};
